### PR TITLE
Dialogue duplicates

### PR DESCRIPTION
**Pull request by sonicdcer**
A few of them were pretty different and i had to decompile some differences.

### CODE REVIEW

**Comment by sonicdcer** [comment]
> There is a lot of duplication and copy & paste. You should start moving the shared code appropriately like in the other PRs from me, sozud and bismurphy.

Yes, I am committed to do it once i got the pattern right, don't worry.

**Comment by sonicdcer** [comment]
Just to be clear, i'm on the same page as you, i don't see myself copy pasting functions across 40 overlays in the future, i agree that it needs to be done, and i will do it.

**Comment by sonicdcer** [comment]
> Then I do not get why you cannot do it now and accept a promise?

As I said before, ill do it once I get the pattern right, which I haven't done yet because I'm focusing on something else, there's also the data problem to go through with deduplicating entity functions that will make everything worse. Please, I need this merged, have more NZ0 functions decompiled waiting for this.

**Comment by sonicdcer** [comment]
> I do not get of what pattern are you talking about. 

Function and data grouping basically.

**Comment by sozud** [comment]
My opinion is that this gets us closer to real deduplication, so it's still worth merging. @sonicdcer Could you reopen this?

**Pull request closed without merging**
