### PR TITLE
Decompile dupe function rwrp func_801A2550

### PR DESCRIPTION
**Pull request by ser-pounce**
Hopefully straightfoward

### CODE REVIEW

**Review by sozud — APPROVED** [review]
Looks good, if you want to go further we have a process to work towards de-duplication where the function and data gets matching names across all the overlays and it gets pulled into an include. Here's an example https://github.com/Xeeynamo/sotn-decomp/pull/459/files

**Comment by ser-pounce** [comment]
I can give it a shot, I suppoe the function needs a name? The `p3` member seems to be (ab)used to store state flags, so the function is something like `getNextXxxPrim` where `Xxx` is whatever is represented by `p3` being 0.

**Comment by sozud** [comment]
I guess reading it what comes to mind is `FindPolyWithP3` or something like that. The name isn't super important and can be documented in more detail as we progress. Also I can merge this and if you want to do the deduplication as a follow up  (or not do it) that's fine.

**Comment by ser-pounce** [comment]
Sounds good! I'll get to work on the refactor.

**Pull request merged**
