### PR TITLE
Add CEN Overlay to HD

### LINKED ISSUE #1638: Add HD overlay for CEN
Refer to the guide on [how to add new overlays](https://github.com/Xeeynamo/sotn-decomp/wiki/Decompilation#add-new-overlay).

The overlay is complete on the `us` build. It should be straightforward to adapt the `us` code to match the `hd` build.

### PR DESCRIPTION
**Pull request by hohle**
Adds the CEN overaly to the HD version of the game.

Resolves #1638.

This uses most, but not all, matching functions. Some were excluded because due to symbols mapping that has not bee completed yet.

Not all data has been imported, and mapping symbols, and data should make many of the remaining functions easy to import.

### CODE REVIEW

**Comment by sozud** [comment]
Seems good except
```
src/st/cen/header.c:25:10: fatal error: sprite_banks.h: No such file or directory
   25 | #include "sprite_banks.h"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
src/st/cen/tile_data.c:4:10: fatal error: tilemap_069EC.h: No such file or directory
    4 | #include "tilemap_069EC.h"
      |          ^~~~~~~~~~~~~~~~~
```
Seems like an issue with sotn-assets integration?

**Comment by hohle** [comment]
Yeah, this is the same issue as before. Looking into it.

**Review by sozud — APPROVED** [review]

**Comment by hohle** [comment]
Matched data from `header`, `e_laydef`, `e_init`, `F890`, `collision`, `e_layout`, `sprites`.

Fixed a misaligned `g_Dialogue` address

Matched several more dups in `F890`, `collision`, `cutscene`, and `e_misc`.

**Comment by sozud** [comment]
Originally I thought Xeeynamo should take a look since there was a lot of #if/else. The updated version is a lot cleaner so I think we can just merge

**Pull request merged**
