### PR TITLE
Migrate .rodata to functions for main.exe

### PR DESCRIPTION
**Pull request by mkst**
I feel like getting all the rodata migrated will make it easier to update splat (also makes it easier to match functions that use rodata).

### CODE REVIEW

**Comment by sozud** [comment]
Looks like I broke it by merging master
```
src/main/psxsdk/libsnd/seqinit.c:(.text+0x348): undefined reference to `D_80010A3C'
mipsel-linux-gnu-ld: src/main/psxsdk/libsnd/seqinit.c:(.text+0x34c): undefined reference to `D_80010A3C'
```

Also note that this PR references some data https://github.com/Xeeynamo/sotn-decomp/pull/1077/files
So if that one gets merged first it should break this one again

**Comment by mkst** [comment]
breaking this is fine, I have a small tweak, let me try and fix things.

**Review by Xeeynamo — APPROVED** [review]
Approved :ok_hand: thanks for doing this! I will give @sozud the freedom to finish reviewing and merge this as he has more knowledge on the moving parts in `main`

**Review by sozud — APPROVED** [review]
Looks good to me, will need a rebase on master now that the other PR is merged though. Thanks for putting up with the PR churn

**Pull request merged**
