### PR TITLE
Implement SetRCnt

### PR DESCRIPTION
**Pull request by joshlory**
https://decomp.me/scratch/jawso

### CODE REVIEW

**Review by sozud — APPROVED** [review]
Nice work, thanks for your contribution!

**Comment by joshlory** [comment]
I'm not sure I have the function signature quite right ... args `u32 spec, u16 target` gives the same assembly.

**Comment by sozud** [comment]
3.5 KERNEL.H says 
```
extern long SetRCnt(unsigned long, unsigned short, long);
```
https://github.com/sozud/psy-q/blob/9f541dbade4b25bcba449aea0e3dac9ab3cde14b/3.5/PSX/INCLUDE/KERNEL.H#L163

The public and internal headers may not be the same though. The manual gives a different signature:
image

**Comment by sozud** [comment]
I think it's fine either way so going to merge.

**Pull request merged**
