### PR TITLE
tt_001 duplicate function decomp

### PR DESCRIPTION
**Pull request by Onenutmcgee**
- Decompiled duplicate function func_us_801714F4
- Decompiled duplicate function func_us_80172904
- Decompiled duplicate function func_us_8017293C (renamed Tt001UpdateAnim per tt_000 duplicate)
- Decompiled duplicate function func_us_80172B50
- Decompiled duplicate function func_us_80172B88
- Added EntitySearch D_80170EE4[] to servant.h to be used by func_us_80172B88 similar to duplicate in tt_000

A lot of these are in the same order in tt_000, so I would assume they could be moved to shared static functions at some point.

### CODE REVIEW

**Comment by sozud** [comment]
Would you mind deduplicating these? The process is similar to this PR: https://github.com/Xeeynamo/sotn-decomp/pull/1556/files

You'll need to unify the function and data names, just doing something simple like UnkFamiliarFunc1 is fine. These need to be added to symbols.txt for both overlays

Then you can pull these out to headers

**Comment by Onenutmcgee** [comment]
Yes, I will do that when I get back on either later tonight or tomorrow.  
Do you happen to know if that will also resolve the issue with the Linter check?  I'm not sure I understand why that one is failing.

**Comment by sozud** [comment]
Run `make format` to fix the linter. Also I started a page on deduplication which may help https://github.com/Xeeynamo/sotn-decomp/wiki/Deduplication

**Comment by Onenutmcgee** [comment]
Sounds good. Thanks for the docs. I’ll get to it after my kiddo goes to bed.

**Comment by Onenutmcgee** [comment]
This ended up being more changes than I had wanted to do with a single PR.  Sorry about that.
I'm not sure what I may have done to destroy the PSP build.

**Comment by sozud** [comment]
Try this to fix psp https://github.com/Xeeynamo/sotn-decomp/commit/e572ac74fd08323586878009c4d4670939360abf

**Review by sozud — APPROVED** [review]
Nice work!

**Pull request merged**
