### PR TITLE
Start documenting sfx scripts

### PR DESCRIPTION
**Pull request by sozud**

### CODE REVIEW

**Review by hohle — APPROVED** [review]
Great!

**Comment by synamaxmusic** [comment]
Don't know if this will help but here's some notes I made when I was looking at the sequence data earlier last year:

```
800C09E8 = First valid multi-note sequence
800C0C00 = Alucard swing
800C0C74 = Level Up sequence
800C0CE8 = UI (7B) sequence
800C1ECC = SfxSeqPtrTable (already in commit 140c637)

80138f70 = sfx spu NoteOn flags (two channels are triggered)
80138f64 = music spu NoteOn flags (one byte per channel)

8013ae84 = current multi-note sequence playing
8013aea0 = current multi-note sequence pitch?
8013aed4 = current single-note sequence
8013B628 = current sequence pointer
8013B648 = current soundID (Channels 0-11)
8013B650 = current soundID (Channels 12-23)

8013b66c = NoteOn timer
```

**Comment by synamaxmusic** [comment]
Also, I think one of the ` g_UnkChannelSetting` might be related to sound panning.

**Review by Xeeynamo — APPROVED** [review]
It looks good! Not sure if you want to integrate some of @synamaxmusic suggestions. Either way I am happy if you merge this when you see it fit

**Comment by sozud** [comment]
I'll investigate synamaxmusic's suggestions and see about a follow-up

**Pull request merged**
