### PR TITLE
Use `e_collect.h` for NP3, CEN, MAD, DRE, ST0

### PR DESCRIPTION
**Pull request by bismurphy**
Came across e_collect.c in NP3, and it wasn't using the e_collect.h, but now it is. Overall just a big deduplication.

### CODE REVIEW

**Comment by bismurphy** [comment]
Noticed I can do the same on CEN, so I think I'm going to just tack that onto this PR.

**Comment by bismurphy** [comment]
Okay, should be good to go as long as CI is happy

**Comment by bismurphy** [comment]
Okay, MAD doesn't match the other overlays, so I couldn't pull in the .h file, but at least this makes the file structure line up.

**Comment by bismurphy** [comment]
Going to keep working on the MAD version and making the functions align as close as possible, in hopes we can end up using e_collect.h in the end.

**Comment by Xeeynamo** [comment]
> Going to keep working on the MAD version and making the functions align as close as possible, in hopes we can end up using e_collect.h in the end.

Let me know when you want this to be reviewed before merging it!

**Review by sozud — APPROVED** [review]

**Comment by bismurphy** [comment]
> > Going to keep working on the MAD version and making the functions align as close as possible, in hopes we can end up using e_collect.h in the end.
> 
> Let me know when you want this to be reviewed before merging it!

Alright I think we're good now! All three overlays I targeted are now working.

**Comment by bismurphy** [comment]
I lied, adding DRE

**Comment by bismurphy** [comment]
Okay now I'm really really done for real, this is the last overlay remaining so I can't possibly make this PR bigger :)

**Comment by hohle** [comment]
Screenshot 2024-08-13 at 8 52 57 AM
so good! (as long as you're [not paid by lines of code](https://www.folklore.org/Negative_2000_Lines_Of_Code.html))

**Review by Xeeynamo — COMMENTED** [review]
`STAGE == STAGE_STAGE_ST0` this might be a fluke. If you look at the beginning of st0.h we have a `#define STAGE STAGE_ST0`. I am not sure how it is supposed to work with `STAGE_STAGE_ST0` :thinking:

Everything else is awesome. Congrats for the fantastic clean-up! I will be happy to get this approved and merged once the mystery behind `STAGE_STAGE_ST0` is solved!

**Comment by bismurphy** [comment]
> `STAGE == STAGE_STAGE_ST0` this might be a fluke. If you look at the beginning of st0.h we have a `#define STAGE STAGE_ST0`. I am not sure how it is supposed to work with `STAGE_STAGE_ST0` 🤔
> 
> Everything else is awesome. Congrats for the fantastic clean-up! I will be happy to get this approved and merged once the mystery behind `STAGE_STAGE_ST0` is solved!

Good catch! I was basing this on collect_gold.h but that was my own mistake from months ago. Should all be fixed now. Thanks for the kind words!

**Pull request merged**
