### PR TITLE
More SFX reference updates

### PR DESCRIPTION
**Pull request by synamaxmusic**
I think we're all caught up with the current sfx enum so the next PR will have some new sfx IDs added.

### CODE REVIEW

**Review by Xeeynamo — COMMENTED** [review]
I did review half of the changes, but I stopped at the stage changes. Have you check that those sound effects are consistent across every overlay despite the same SFX ID?

**Review by sozud — APPROVED** [review]

**Comment by sozud** [comment]
> I did review half of the changes, but I stopped at the stage changes. Have you check that those sound effects are consistent across every overlay despite the same SFX ID?

Stage sfx are in vabid 3, I think all these are vab 0 so there's no conflict

**Comment by synamaxmusic** [comment]
Yup, once we get to `0x709` then we'll have to start analysis how the sound effects are used in the stages.

**Comment by Xeeynamo** [comment]
Oh wow I did not know. It's crazy how this project grew so big that there are no people that understand every portion of the game.

**Comment by sozud** [comment]
This got conflicted, can you rebase it?

**Comment by synamaxmusic** [comment]
I see what happened, fixing now.

**Pull request merged**
