### PR TITLE
Sonicdcer EntityCSMoveAlucard

### PR DESCRIPTION
**Pull request by sozud**
I'm putting these back up so the work isn't lost. @Xeeynamo are you fine with merging this since we haven't come up with a solution for `D_80097400`?

### CODE REVIEW

**Comment by sozud** [comment]
Rebased but needs this fixed
```
mipsel-linux-gnu-ld: build/us/asm/us/st/dre/data/118D0.rodata.s.o: in function `jtbl_801918D0':
(.rodata+0x0): undefined reference to `.L801962CC'
mipsel-linux-gnu-ld: (.rodata+0x4): undefined reference to `.L80196324'
mipsel-linux-gnu-ld: (.rodata+0x8): undefined reference to `.L801963D8'
mipsel-linux-gnu-ld: (.rodata+0xc): undefined reference to `.L80196470'
mipsel-linux-gnu-ld: (.rodata+0x10): undefined reference to `.L801964B8'
mipsel-linux-gnu-ld: (.rodata+0x14): undefined reference to `.L80196564'
mipsel-linux-gnu-ld: (.rodata+0x18): undefined reference to `.L80196594'
mipsel-linux-gnu-ld: (.rodata+0x1c): undefined reference to `.L801965D4'
mipsel-linux-gnu-ld: (.rodata+0x20): undefined reference to `.L80196604'
```

**Review by Xeeynamo — CHANGES_REQUESTED** [review]
We eventually found `D_80097400` is part of `g_unkGraphicsStruct` (thanks to @bismurphy for the discovery), so that should put an end on the mystery around it. @sozud and @sonicdcer how do you feel on merging/rebasing this PR versus create a completely new PR?

**Comment by sozud** [comment]
Not sure if I'm doing it wrong but it seems like 0x80097400 is not in a struct? See C line 119 https://decomp.me/scratch/nEdAS

**Comment by bismurphy** [comment]
> Not sure if I'm doing it wrong but it seems like 0x80097400 is not in a struct? See C line 119 https://decomp.me/scratch/nEdAS

You need to also use g_unkGraphicsStruct.unkC instead of D_8009740C. See here: https://decomp.me/scratch/0msAo

**Comment by sozud** [comment]
Thanks, does anyone see what I'm doing wrong with my file split?

https://github.com/Xeeynamo/sotn-decomp/compare/master...sozud:sotn-decomp:Ent21

```
mipsel-linux-gnu-ld: build/us/asm/us/st/dre/data/0.data.s.o: in function `PfnEntityUpdates':
(.data+0x448): undefined reference to `EntityUnkId21'
mipsel-linux-gnu-ld: (.data+0x450): undefined reference to `EntityUnkId23'
mipsel-linux-gnu-ld: build/us/asm/us/st/dre/data/118D0.rodata.s.o: in function `jtbl_801918D0':
(.rodata+0x0): undefined reference to `.L801962CC'
mipsel-linux-gnu-ld: (.rodata+0x4): undefined reference to `.L80196324'
mipsel-linux-gnu-ld: (.rodata+0x8): undefined reference to `.L801963D8'
mipsel-linux-gnu-ld: (.rodata+0xc): undefined reference to `.L80196470'
mipsel-linux-gnu-ld: (.rodata+0x10): undefined reference to `.L801964B8'
mipsel-linux-gnu-ld: (.rodata+0x14): undefined reference to `.L80196564'
mipsel-linux-gnu-ld: (.rodata+0x18): undefined reference to `.L80196594'
mipsel-linux-gnu-ld: (.rodata+0x1c): undefined reference to `.L801965D4'
mipsel-linux-gnu-ld: (.rodata+0x20): undefined reference to `.L80196604'
mipsel-linux-gnu-ld: build/us/asm/us/st/dre/data/118D0.rodata.s.o: in function `jtbl_801918F8':
(.rodata+0x28): undefined reference to `.L801966BC'
mipsel-linux-gnu-ld: (.rodata+0x2c): undefined reference to `.L8019671C'
mipsel-linux-gnu-ld: (.rodata+0x30): undefined reference to `.L8019683C'
mipsel-linux-gnu-ld: (.rodata+0x34): undefined reference to `.L80196888'
mipsel-linux-gnu-ld: (.rodata+0x38): undefined reference to `.L801968E4'
mipsel-linux-gnu-ld: (.rodata+0x3c): undefined reference to `.L8019692C'
make: *** [Makefile:274: build/us/stdre.elf] Error
```

**Comment by bismurphy** [comment]
> Thanks, does anyone see what I'm doing wrong with my file split?
> 
My PR here: https://github.com/Xeeynamo/sotn-decomp/pull/1304 splits the files in DRE and should put the rodata for your file in good shape, maybe it makes sense to pull in my PR first and then that will open the door to this one?

**Comment by sozud** [comment]
@bismurphy I still can't figure out the file splits, since you're working on DRE anyway would you mind reviving this?

**Comment by sozud** [comment]
Fixed by https://github.com/Xeeynamo/sotn-decomp/pull/1307

**Pull request closed without merging**
