### PR TITLE
Mark SEL handwritten functions as asm

### PR DESCRIPTION
**Pull request by sozud**

### CODE REVIEW

**Comment by sozud** [comment]
It looks like analyze_calls isn't able to handle jumping to an asm function

```
/* 398F8 801B98F8 E9EA060C */  jal        DecDCTvlc
glabel StreamNextVlc
Failed to return a value
```

**Comment by sozud** [comment]
@bismurphy Would you mind looking at the analyze_calls issue when you have a chance?

**Comment by bismurphy** [comment]
Looking now, got the failure replicated locally and will work on diagnosing and fixing. Thanks for the ping.

**Comment by sozud** [comment]
@Xeeynamo Do you have any issues with this change? https://github.com/Xeeynamo/sotn-decomp/pull/977/commits/93c4cdf0f685124af9b693665b44f7ea011372c7
The point is coordinating with https://github.com/sozud/sotn-decomp/pull/1

**Comment by sozud** [comment]
When using hasm some of the asm directives aren't added

```
/* Generated by spimdisasm 1.18.0 */

# Handwritten function
glabel DecDCTvlc
```
```
asm/us/st/sel/handwritten/DecDCTvlc.s: Error: .size expression for DecDCTvlc does not evaluate to a constant
```

If I add

```
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
```

it still fails

```
asm/us/st/sel/handwritten/DecDCTvlc.s:6: Error: unrecognized opcode `glabel DecDCTvlc'
asm/us/st/sel/handwritten/DecDCTvlc.s: Error: .size expression for DecDCTvlc does not evaluate to a constant
make: *** [Makefile:419: build/us/asm/us/st/sel/handwritten/func_801BAB70.s.o] Error 1
```

If I fix the extraction of func_801BAB70, we get this:

```
.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.18.0 */

# Handwritten function
glabel func_801BAB74
/* 3AB74 801BAB74 1C80083C */  lui        $t0, %hi(func_801BAB70)
/* 3AB78 801BAB78 70AB0825 */  addiu      $t0, $t0, %lo(func_801BAB70)
/* 3AB7C 801BAB7C FFFF8120 */  addi       $at, $a0, -0x1 # handwritten instruction
/* 3AB80 801BAB80 04002018 */  blez       $at, .L801BAB94
/* 3AB84 801BAB84 0000028D */   lw        $v0, 0x0($t0)
/* 3AB88 801BAB88 40080400 */  sll        $at, $a0, 1
/* 3AB8C 801BAB8C 0800E003 */  jr         $ra
/* 3AB90 801BAB90 000001AD */   sw        $at, 0x0($t0)
.L801BAB94:
/* 3AB94 801BAB94 FF00013C */  lui        $at, (0xFFFFFF >> 16)
/* 3AB98 801BAB98 FFFF2134 */  ori        $at, $at, (0xFFFFFF & 0xFFFF)
/* 3AB9C 801BAB9C 0800E003 */  jr         $ra
/* 3ABA0 801BABA0 000001AD */   sw        $at, 0x0($t0)
.size func_801BAB74, . - func_801BAB74
```

The addi is still marked as handwritten. The data at 0x801BAB70 is loaded at the beginning of the function

**Pull request merged**
