### PR TITLE
SFX defines for RIC, Teleport, CrossCrash

### PR DESCRIPTION
**Pull request by synamaxmusic**

### CODE REVIEW

**Comment by sozud** [comment]
I think that we need to reorganize our sound effects. Given this:

```
#if defined(VERSION_BETA)
#define SFX_OPEN_DOOR 0x640
#define SFX_DOOR_UNKNOWN 0x64D
#else
#define SFX_OPEN_DOOR 0x642
```

`SFX_OPEN_DOOR` moved from 0x640 to 0x642 during development. I think this means these were an enum originally.

Even though there are multiple VABs, it seems they they just added to that single enum. For example in assets/dra/sfx.json:

```
            "id_hex": "2CC",
            "vabid": 9,
            "id_hex": "2CD",
            "vabid": 0,
            "id_hex": "2CE",
            "vabid": 0,
            "id_hex": "2CF",
            "vabid": 0,
            "id_hex": "2D0",
            "vabid": 3,
```

I think somehow we ought to differentiate the vabs. Vab 0 is the "system" vab and is always loaded. 1 is richter or alucard. 2 is the familiar or maria apparently? 3 is the stage. 9 seems to be unused or left over? See:

```
CdFile g_LbaSdAlkVh = {0x615B, 19, 0x01020, 1, 1, 0xFF, 7};
CdFile g_LbaSdAlkVb = {0x615E, 17, 0x0E1D0, 1, 1, 0xFF, 0};
CdFile g_LbaSdRihVh = {0x617B, 19, 0x01020, 1, 1, 0x16, 21};
CdFile g_LbaSdRihVb = {0x617E, 17, 0x0CC20, 1, 1, 0xFF, 0};
CdFile g_LbaSdMarVh = {0x6198, 19, 0x00E20, 2, 2, 0xFF, 23};
CdFile g_LbaSdMarVb = {0x619A, 17, 0x0E290, 2, 2, 0xFF, 0};
CdFile g_LbaSdJ010_1_Vh = {0x60D0, 19, 0x02A20, 0, 0, 0x0A, 9};
CdFile g_LbaSdJ010_1_Vb = {0x60D6, 17, 0x41CB0, 0, 0, 0xFF, 0};
CdFile g_LbaSdJ010_2_Vh = {0x60D0, 19, 0x41CB0, 4, 4, 0x0C, 11};
CdFile g_LbaSdJ010_2_Vb = {0x60D6, 17, 0x1A510, 4, 4, 0x0C, 0};
CdFile g_LbaStageVh = {0x0000, 19, 0x00000, 3, 3, 0xFF, 14};
CdFile g_LbaStageVb = {0x0000, 17, 0x00000, 3, 3, 0xFF, 0};
CdFile g_LbaSdJ010_3_Vh = {0x60D0, 19, 0x02A20, 3, 3, 0xFF, 16};
CdFile g_LbaSdJ010_3_Vb = {0x60D6, 17, 0x41CB0, 3, 3, 0xFF, 0};

...
CdFile g_LbaServantVh = {0x0000, 19, 0x00000, 2, 2, 0xFF, 30};
CdFile g_LbaServantVb = {0x0000, 17, 0x00000, 2, 2, 0xFF, 0};
```

Not sure what the deal is with the SdJ010 ones.

@Xeeynamo Any opinions here?

**Comment by synamaxmusic** [comment]
How would implementing and using enums for sound IDs look like compared to using #define?  

My biggest concern is how sound IDs tend to get reused for vastly different events or entities.  For example 0x636 is used _at least_ four different times (Teleport End Crash / Dracula Teleport Beam / Warp Enter / Power of Sire End),  

Another example is 0x780.  This is the Warg Wolf Death Howl but it's also used during the second phase of Scylla Worm.

While having multiple #defines for one sound ID can be potentially messy, it can make the code easier to read for situations like this.  And of course, there's also the fact that we also have unused sound IDs that are never referenced in the codebase, but do playback unused sounds in-game like Maria's unused dialogue (0x87F).

**Comment by Xeeynamo** [comment]
We could start using an enum, yeah. So for each version that adds or removes an entry, it gets adjusted automatically.

> Which version of the game is considered the beta?

It's the MAD.BIN overlay. It seems to precede the very first game release.

**Comment by sozud** [comment]
I can't test it but I wrote a script to generate an enum with a comment for the vabid https://gist.github.com/sozud/59264034bd2972214cc1f27b41e49481

```
import json

with open('assets/dra/sfx.json', 'r') as f:
    data = json.load(f)

def format_output(data):
    for asset in data['asset_data']:
        id = format(asset['id'] + 0x601, 'X')
        print(f"SFX_UNK_{id}, // vabid {asset['vabid']}")

format_output(data)
```

**Comment by synamaxmusic** [comment]
So would using an enum allow duplicate entries?

**Comment by sozud** [comment]
> So would using an enum allow duplicate entries?

Can you give examples of duplicates we know about?

**Comment by synamaxmusic** [comment]
> > So would using an enum allow duplicate entries?
> 
> Can you give examples of duplicates we know about?

I already gave some examples here:
https://github.com/Xeeynamo/sotn-decomp/pull/1441#issuecomment-2253659807

So 0x636 sounds like an anime sword/light beam effect, right?  But it's used in Warp rooms as the starting sound cue, while teleport effects tend to use the cue at the end of the animation.  

Defining this sound ID as `SFX_ANIME_SOUND` or something generic might make things more confusing overtime.

I've linked this before but here's the list of all the sound IDs I've documented so far: https://docs.google.com/spreadsheets/d/1ZSeAV5zVFxFkxg4eWxi7iukVHHXaEZlif5vjXRiTeww/edit?usp=sharing

**Comment by sozud** [comment]
> My biggest concern is how sound IDs tend to get reused for vastly different events or entities. For example 0x636 is used at least four different times (Teleport End Crash / Dracula Teleport Beam / Warp Enter / Power of Sire End),
```
SFX_UNK_636, // vabid 0
```
It's vab 0 so I'd expect it to be used a bunch of times. I think they would have just picked a name like SFX_TELEPORT or whatever.

> Another example is 0x780. This is the Warg Wolf Death Howl but it's also used during the second phase of Scylla Worm.
```
SFX_UNK_780, // vabid 3
```
It's vab 3 so it belongs to the stage vab. My best guess is that once they created a vab, they duplicated it and then changed whatever sounds needed to be changed. So as long as that sfx ID pointed to the correct vab, program and tone, there was no reason to make a new ID.

**Comment by synamaxmusic** [comment]
I guess I can try to come up with some more generic names for the vabid 0 sounds.  Perhaps I can use comments to put in more details if needed.

Are there only four 4 VABs loaded in memory during gameplay?  I'm assuming vabid 3 is either `800b607c` or `800b807c`.  

Thanks for that generated enum, knowing which sounds use vabid 3 is good to know; maybe we can find a pattern by switching overlays.

**Comment by synamaxmusic** [comment]
https://gist.github.com/synamaxmusic/161fa7343c75bc6845aa6c0039fab7cb 

Here's my work in progress on the enum names

**Comment by sozud** [comment]
> `800b607c`
```
    LOAD_VAB(0, aPbav, g_VabAddrs[0], D_8013B6A0, vab0Len);
    LOAD_VAB(1, aPbav_0, g_VabAddrs[1], D_8017D350, vab1Len);
    LOAD_VAB(2, aPbav_1, g_VabAddrs[2], D_801A9C80, vab2Len);
    LOAD_VAB(3, aPbav_2, g_VabAddrs[3], D_8018B4E0, vab3Len);
```
```
aPbav_2 = 0x800B607C;
```
The initial vab 3 is aPbav_2, but that gets overwritten later

> Are there only four 4 VABs loaded in memory during gameplay?

As far as I know yes.

> Here's my work in progress on the enum names

We don't have to do everything at once, I just meant that given the evidence it seems like it ought to be an enum. It can just be one entry to start e.g.
```
enum Sfx
{
SFX_NEW_ONE=0xXXXX
};
```

**Comment by synamaxmusic** [comment]
Gonna close this request and open up a new one with the enum implemented.  Thanks to everyone for your help and suggestions!

**Pull request closed without merging**
