### PR TITLE
Add saturn function finder script

### PR DESCRIPTION
**Pull request by sozud**
This does basically the same thing as the PSX one except I went with markdown for nicer formatting. The script has to do enough things differently I thought it would be cleaner to keep them separate. An example output is at https://github.com/sozud/sotn-decomp/blob/saturn_function_finder/funcs_sat.md

I ignore functions from 0.BIN in the SEGA libraries section. This doesn't integrate with the CI yet since it's hard to test on my branch.

### CODE REVIEW

**Review by sonicdcer — APPROVED** [review]
This is amazing, and i love the Markdown touch.

**Comment by sozud** [comment]
Well the raw file looks like this. https://raw.githubusercontent.com/sozud/sotn-decomp/saturn_function_finder/funcs_sat.md

If I improve the padding would that be acceptable? We could also have the option of plain text or markdown output, it's not that hard to do.

**Comment by sozud** [comment]
I adjusted this to have better raw formatting, see here: https://gist.github.com/sozud/810c55e202b71981bb1ff8ecf1f985f3
I also added a --no-fetch argument to avoid fetching from decomp.me. Your workflow could be like this for example

```
python3 tools/function_finder_saturn.py --no-fetch | grep -e t_bat -e Filename -e \|-
| Filename                     | Function Name | Length | Branches | WIP | % |
|------------------------------|---------------|--------|----------|-----|---|
| t_bat/f_nonmat/f60D11DC.s    | func_060D11DC | 43     | 3        |     |   |
| t_bat/f_nonmat/f60D1808.s    | func_060D1808 | 48     | 8        |     |   |
| t_bat/f_nonmat/f60CF294.s    | func_060CF294 | 51     | 7        |     |   |
| t_bat/f_nonmat/f60D125C.s    | func_060D125C | 51     | 7        |     |   |
| t_bat/f_nonmat/f60D1784.s    | func_060D1784 | 77     | 10       |     |   |
| t_bat/f_nonmat/f60D1640.s    | func_060D1640 | 80     | 4        |     |   |
| t_bat/f_nonmat/f60D16D0.s    | func_060D16D0 | 103    | 15       |     |   |
| t_bat/f_nonmat/f60CF5F4.s    | func_060CF5F4 | 104    | 4        |     |   |
| t_bat/f_nonmat/f60D0968.s    | func_060D0968 | 126    | 4        |     |   |
| t_bat/f_nonmat/f60CF2E8.s    | func_060CF2E8 | 164    | 10       |     |   |
| t_bat/f_nonmat/f60D12DC.s    | func_060D12DC | 170    | 30       |     |   |
| t_bat/f_nonmat/f60D1070.s    | func_060D1070 | 176    | 14       |     |   |
| t_bat/f_nonmat/f60CFB00.s    | func_060CFB00 | 181    | 13       |     |   |
| t_bat/f_nonmat/f60CF410.s    | func_060CF410 | 258    | 16       |     |   |
| t_bat/f_nonmat/f60D141C.s    | func_060D141C | 301    | 44       |     |   |
| t_bat/f_nonmat/f60CF060.s    | func_060CF060 | 317    | 40       |     |   |
| t_bat/f_nonmat/f60CF6B4.s    | func_060CF6B4 | 610    | 44       |     |   |
| t_bat/f_nonmat/f60D0490.s    | func_060D0490 | 643    | 49       |     |   |
| t_bat/f_nonmat/f60D0A64.s    | func_060D0A64 | 781    | 59       |     |   |
| t_bat/f_nonmat/f60CFC48.s    | func_060CFC48 | 1146   | 120      |     |   |
```

I also added an --overlay argument so you could also do this:
```
python3 tools/function_finder_saturn.py --no-fetch --overlay t_bat
| Filename                  | Function Name | Length | Branches | WIP | % |
|---------------------------|---------------|--------|----------|-----|---|
| t_bat/f_nonmat/f60D11DC.s | func_060D11DC | 43     | 3        |     |   |
| t_bat/f_nonmat/f60D1808.s | func_060D1808 | 48     | 8        |     |   |
| t_bat/f_nonmat/f60CF294.s | func_060CF294 | 51     | 7        |     |   |
| t_bat/f_nonmat/f60D125C.s | func_060D125C | 51     | 7        |     |   |
| t_bat/f_nonmat/f60D1784.s | func_060D1784 | 77     | 10       |     |   |
| t_bat/f_nonmat/f60D1640.s | func_060D1640 | 80     | 4        |     |   |
| t_bat/f_nonmat/f60D16D0.s | func_060D16D0 | 103    | 15       |     |   |
| t_bat/f_nonmat/f60CF5F4.s | func_060CF5F4 | 104    | 4        |     |   |
| t_bat/f_nonmat/f60D0968.s | func_060D0968 | 126    | 4        |     |   |
| t_bat/f_nonmat/f60CF2E8.s | func_060CF2E8 | 164    | 10       |     |   |
| t_bat/f_nonmat/f60D12DC.s | func_060D12DC | 170    | 30       |     |   |
| t_bat/f_nonmat/f60D1070.s | func_060D1070 | 176    | 14       |     |   |
| t_bat/f_nonmat/f60CFB00.s | func_060CFB00 | 181    | 13       |     |   |
| t_bat/f_nonmat/f60CF410.s | func_060CF410 | 258    | 16       |     |   |
| t_bat/f_nonmat/f60D141C.s | func_060D141C | 301    | 44       |     |   |
| t_bat/f_nonmat/f60CF060.s | func_060CF060 | 317    | 40       |     |   |
| t_bat/f_nonmat/f60CF6B4.s | func_060CF6B4 | 610    | 44       |     |   |
| t_bat/f_nonmat/f60D0490.s | func_060D0490 | 643    | 49       |     |   |
| t_bat/f_nonmat/f60D0A64.s | func_060D0A64 | 781    | 59       |     |   |
| t_bat/f_nonmat/f60CFC48.s | func_060CFC48 | 1146   | 120      |     |   |
```

**Comment by sozud** [comment]
Going to merge and attempt to set this up with the CI. If there are issues with the formatting I can do a follow-up.

**Pull request merged**
